version: '3'

services:
        dbos:
                image: mysql:5.7
                volumes:
                        - mysql_storage_new:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: sid
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: mydb
           
        admineros:
                image: adminer:latest
                restart: always
                depends_on:
                        - dbos
                ports:
                        - 8080:80
                environment:
                        ADMINER_DESIGN: nette


